name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'kjxbyz/ts-lib-starter'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Publish
        run: pnpm publish --publish-branch main --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
