name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x, 22.x]

    runs-on: ${{ matrix.os }}
    environment: ${{ github.event_name == 'push' && 'Production' || 'Preview' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false

      - name: Install Dependencies
        run: |
          npm i -g corepack
          corepack enable
          pnpm install

      # Runs a set of commands using the runners shell
      - name: Build and Test
        run: pnpm test
